IDEA_REFS = {
 "migrate": ["An Empirical Study on the Classification of Bug Reports",
             "Redefining Elderly Care With Agentic AI",
             "LLM-Driven Adaptive Cloud Resource Scheduling",
             "Integrating AI and Large Language Models for Automated Data Quality Enhancement",
             "Applicability of Process Mining in Usability Tests"],
 "retrieval":["Gaussian Kernel-Based LSH for High-Dimensional Similarity Search",
             "Include-Slim",
             "A Framework for Predictive Similarity Queries Over Heterogeneous Metric Spaces",
             "H2-Cache",
             "SINdex"],
 "forecast":["A Hybrid Temporal Convolutional Network and Transformer Model",
             "An Enhanced Deep Learning Approach to Potential Purchaser Prediction",
             "Comprehensive Electricity Demand Forecasting",
             "BOL-LPP",
             "CryptoMamba-SSM",
             "LaplaceSalesNet",
             "ECommVis"],
 "aiops":   ["A Multi-Task Neural Framework for Unified Alert Processing",
             "Cross-Modal Attention Networks for Multi-Modal Anomaly Detection",
             "A Physics-Guided Bayesian Neural Network for Sensor Fault Detection",
             "DRL-Adapt",
             "Human-in-the-Loop Feature Selection Using Interpretable Kolmogorov-Arnold",
             "Benchmarking Explainable AI Methods for Vision Transformer"],
 "energy":  ["LLMs on a Budget",
             "Idle Fragmentation-Aware Resource Scheduling",
             "DeCLIP",
             "LLM-Driven Adaptive Cloud Resource Scheduling",
             "An Efficient Neural Cell Architecture for Spiking Neural Networks",
             "NA-STM Enhanced Energy-Efficient Custom Spiking U-Net"],
 "degrade": ["Cross-Modal Attention Networks for Multi-Modal Anomaly Detection",
             "Leveraging Deep Learning and Multimodal Large Language Models for Near-Miss",
             "A Multimodal Self-Supervised Learning Framework for Scene Understanding",
             "An Emotion Aware Driving Assistant Using Multimodal Recognition",
             "Advancing Autism Spectrum Disorder Diagnosis With Multimodal Data",
             "A Physics-Guided Bayesian Neural Network for Sensor Fault Detection"],
}
